Allow spaces in name attributes.
opsgenie/terraform-provider-opsgenie pull request #18
Opened 2019-09-11 13:27 UTC by gfl-chris

2019-09-11 15:19 UTC, ffahri requested changes

2019-09-11 15:19 UTC, ffahri commented on opsgenie/integration_util.go
> -	if !regexp.MustCompile(`^[a-zA-Z0-9_-]+$`).MatchString(value) {
this line is not correct and not a true statement in terms of regex also throws compilation error

2019-09-11 15:19 UTC, ffahri commented on opsgenie/resource_opsgenie_schedule.go
> +	if !regexp.MustCompile(`^[a-zA-Z0-9_- ]+$`).MatchString(value) {
Same as integrationutil also not correct

2019-09-11 15:19 UTC, ffahri commented on opsgenie/resource_opsgenie_team.go
> +	if !regexp.MustCompile(`^[a-zA-Z0-9_- ]+$`).MatchString(value) {
wrong statement

2019-09-11 15:23 UTC, ffahri commented
Thank you for pointing about this bug

2019-09-11 15:34 UTC, ffahri commented
It should be good if you change it to `a-zA-Z 0-9_-` (space in the middle)

2019-09-13 11:28 UTC, ffahri commented
the fix has added to master thank you for help

2019-09-13 11:28 UTC, closed without merging

2019-09-13 19:19 UTC, gfl-chris commented
Thank you. :+1: