Refactor `time_restriction` and stabilise plans containing `notification_rule.steps`, `notification_policy.filter.conditions` and `time_restrictions`
opsgenie/terraform-provider-opsgenie pull request #404
Opened 2023-10-21 16:58 UTC by Baarsgaard

The first two commits closes #246 and #253 respectively.
The second commit also adds some much needed schema validation for the Terraform-ls to use.

The third commit unifies the schema and the handling of expanding/flattening `time_restriction` blocks.
It also closes #341 which fixes  unstable plans using `time_restriction`
Additionally, I added standard validation rules for `time_restriction` blocks as well as schema rules.

This is a pretty big PR solely because of the `time_restriction` refactor, I am willing to split it, but I do still think reviewing this PR one commit at a time is feasible.

2023-10-25 18:52 UTC, Baarsgaard commented
@koushik-swaminathan Sorry to ping you, but I would like to have this merged to continue using the provider :)

2023-10-26 09:39 UTC, koushik-swaminathan commented
@Baarsgaard sure, I'll take a look. Have you tested these changes?

2023-10-26 10:41 UTC, Baarsgaard commented
> @Baarsgaard sure, I'll take a look. Have you tested these changes?

Yes, luckily very little of the actual business logic has actually changed.
The only new code is the `resourceOpsGenieNotificationPolicyMultiValueValidation` the rest is mainly just refactoring and Schema validation updates.

2023-11-02 10:59 UTC, koushik-swaminathan commented
LGTM, tested it as well. But it looks like it doesn't really fix the conditions in-place issues, but time-restriction seems to be stable now.

2023-11-02 16:53 UTC, Baarsgaard commented
Could you share what specifically does not work?
I've been testing with a fair amount of notification policies and I'm unable to get the perpetual state drift to show up:

<details>
<summary>Terminal cast</summary>

[![asciicast](https://asciinema.org/a/trZYQYc4jusQN7limWlXVozV1.svg)](https://asciinema.org/a/trZYQYc4jusQN7limWlXVozV1)

</pre>
</details>

2023-11-03 09:28 UTC, koushik-swaminathan commented
Hi @Baarsgaard, the in-place update issue with condition still persists. Could you try creating this policy once and try applying the policy again without any changes? Ideally there should be no updates, but the provider tries to update the infrastructure.
`resource "opsgenie_team" "test" {
  name        = "example team"
  description = "This team deals with all the things"
}

resource "opsgenie_notification_policy" "test" {
  name               = "example policy"
  team_id            = opsgenie_team.test.id
  policy_description = "This policy has a delay action"
  delay_action {
    delay_option = "next-time"
    until_minute = 1
    until_hour   = 9
  }
  filter {
    type = "match-all"
    conditions {
      field     = "message"
      operation = "contains"
    }
  }
}`
Steps to recreate:
1. `terraform apply` - Policy should get created
2. `terraform apply` - Policy is being updated in place although there are no changes in the infrastructure.

2023-11-03 10:29 UTC, koushik-swaminathan requested changes
Could you edit the date and version in the changelog? I'll merge the PR after that. Thank you!

2023-11-03 12:24 UTC, Baarsgaard commented
I'll set it for Monday next week 2023-11-06

2023-11-03 17:55 UTC, Baarsgaard commented
@koushik-swaminathan Should be ready for a merge now! :D

2023-11-04 10:34 UTC, Baarsgaard commented
> LGTM, tested it as well. But it looks like it doesn't really fix the conditions in-place issues, but time-restriction seems to be stable now.

I was thinking about what could be the cause of this.
The difference is likely that the policies I created were saved as a set, but your test was made on policies stored as the old list.

If you run `terraform apply -refresh-only` followed by a normal `terraform apply` is the plan still unstable?

2023-11-06 07:28 UTC, koushik-swaminathan approved these changes
LGTM!

2023-11-06 07:35 UTC, merged