removed timezone from opsgenie_team_routing_rule resource
opsgenie/terraform-provider-opsgenie pull request #72
Opened 2020-02-29 08:19 UTC by dtomasi

Solves #71

2020-03-02 19:29 UTC, ffahri commented
Hey we have timezone field in team routing rule api 
https://docs.opsgenie.com/docs/team-routing-rule-api

```
Timezone of team routing rule. If timezone field is not given, account timezone is used as default. You can refer to Supported Locale IDs for available timezones. More information about timezones can be found in Time Constraints and Timezones document.
```

2020-03-02 19:32 UTC, ffahri requested changes

2020-03-02 19:32 UTC, ffahri commented on opsgenie/resource_opsgenie_team_routing_rule.go
> -				Required: true,
we need to change required to optional. Because like the error msg says we cannot set timezone for default rule

2020-03-27 16:39 UTC, alessandrotrisolini commented
hey @dtomasi, any chance to implement the change @ffahri requested?

2020-08-19 12:12 UTC, closed without merging