Fix opsgenie_schedule_rotation resource import
opsgenie/terraform-provider-opsgenie pull request #88
Opened 2020-03-19 13:26 UTC by alessandrotrisolini

After importing existing `opsgenie_schedule_rotation` resources into terraform state, some attributes are missing and `terraform plan` shows that they have to be created even if they have been already configured.

This PR will fix this issue by introducing reading support for `time_restriction`, `length`, `name`, and `end_date` attributes .

2020-03-23 12:36 UTC, ffahri requested changes
thanks for this pr 

```
 INFO[2020-03-23T12:33:26.174327654Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:26.294299506Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:26.297170629Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:26.297841047Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:27.291805674Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:27.349621553Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:27.520486269Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:28.075740667Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
INFO[2020-03-23T12:33:28.15535018Z] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10 
panic: interface conversion: interface {} is *schema.Set, not []interface {}
```

TestAccOpsGenieScheduleRotation_basic
TestAccOpsGenieScheduleRotation_complete

test are failing in e2e test

2020-03-25 14:46 UTC, alessandrotrisolini commented
@ffahri thanks for your reply - now e2e are passing.

2020-04-10 09:43 UTC, ffahri approved these changes

2020-04-10 09:43 UTC, ffahri approved these changes

2020-04-10 09:45 UTC, merged